:source-highlighter: rouge


== MEP04: Generators

In this MEP we define the structure of a generator. A generator has the task of
creating notes from a data structure with all the necessary information about a
card. The creation of a note involves the creation of an object that will later
be handled by the packager and the preparation of any multimedia file
associated with the card (images or sound generation).

The terminology "card" and "note" are inherited from Anki. A card is basically
a high-level structure containing data and information on how to create notes.
Notes are what we finally see and study. For example, imagine you are learning
Spanish, your card for "hello" would be represented by the top square in the
following diagram. From that card two notes would be generated, one with
English on the front and one with Spanish on the front. It is very common even
in the documentation to find that we talk about cards when we should say notes.
Although this nomenclature can be confusing, we hope that from the context it
is clear what exactly is being referred to.

// Edit this diagram in https://asciiflow.com/
....
    ┌───────────────────────────┐
    │  your_language: Hello     │
    │  language_you_learn: Hola │
    └───┬────────────────────┬──┘
        │                    │
        ▼                    ▼
 ┌───────────┐          ┌───────────┐
 │   Hola    │          │   Hello   │
 │ --------- │          │ --------- │
 │   Hello   │          │   Hola    │
 └───────────┘          └───────────┘
....

A generator needs two things to work: a correct definition of what input data
is expected and the instructions for converting that input data into a note.


=== Input data validation

One design option would be to define generators as a class with a generate
method that accepts a dictionary. That dictionary should contain everything
necessary to generate a card from it, i.e. our class would be assuming that the
dictionary passed to it would have all the required data and in the correct
data type.

.generator.py
[source,python]
----
class Generator:
    def generate(card_data: dict) -> Note:
        pass
----


=== Generator class

A generator is a class with two main methods: validate and generate.

.generator.py
[source,python]
----
class Generator:
    def validate(card_properties):
        return card_properties

    def generate(card_properties):
        return Note
----

The validate method receives a dictionary as input and applies a schema. The
validate method shall return a dictionary with the card_properties correctly
validated and with all default values populated.

Alternatively, instead of a validate method, a schema could be defined and
Mnemocards could be in charge of validating that the dictionary returned by the
reader complies with the restrictions imposed by the schema.  To do this, we
would have to look for a library to validate schemas on dictionaries.  The
approach is not yet fully decided and will be refined in future editions of
this MEP.

The generate method receives a dictionary with the card properties already
validated and creates the Notes, i.e. it creates the objects that are required
by Genanki to generate the apkg.

Instead of receiving a dictionary as input, validate could return a dataclass
and use that object as input for this function.  This way the input object has
a structure that even linter itself would be able to understand.

Again, this is something yet to be defined.  For the moment this MEP is just an
overview of the proposed approach.

Although we could separate these methods into two distinct classes, making each
class do only one thing, I don't think that would provide any advantage at this
point. What's more, it would probably complicate the code unnecessarily.
