name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      # * is a special character in YAML so we need to quote this string
      - "*"
  pull_request:
    branches:
      - main
  schedule:
    # * is a special character in YAML so we need to quote this string
    - cron: "0 0 * * SUN"

defaults:
  run:
    shell: bash  # Avoid PowerShell on Windows

jobs:
  lint_and_test:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          #- windows-latest  # Windows not working yet
        python-version:
          - "3.10"  # quotes are needed here or the last 0 will be ignored
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup Node (for Pyright)
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.2.0
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install Python Requirements
        run: make install
      - name: Run Formatters and Linters
        run: make format_and_lint
      - name: Run Tests
        run: make test
      - name: Build Wheel
        run: make build
      - name: Upload Wheel to GitHub Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - name: Upload Coverage
        uses: codecov/codecov-action@v2

  build_docs:
    name: Build Docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          #- windows-latest  # Windows not working yet
        python-version:
          - "3.10"  # quotes are needed here or the last 0 will be ignored
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.2.0
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install Python Requirements
        run: make install
      - name: Build Docs
        run: make doc
      - name: Upload Docs to GitHub Artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: site

  deploy:
    name: Deploy
    needs:
      - lint_and_test
      - build_docs
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"  # quotes are needed here or the last 0 will be ignored
      - name: Get All Artifacts
        uses: actions/download-artifact@v3
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.2.0
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install Python Requirements
        run: make install
      - name: Publish Docs
        run: make doc-publish
      - name: Publish PyPi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          make publish
